<?php
$this->headTitle('Ustawienia');

$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
            'Strona główna'=>$this->url('home'),
            'Ustawienia'=>$this->url('application', ['action'=>'settings']),
            ]);
?>

<h2>Ustawienia</h2>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></td>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></td>
            </tr>
            <tr>
                <th>Nazwa:</th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></td>
            </tr>
            <tr>
                <th>Data utworzenia:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></td>
            </tr>
        </table>
    </div>
</div>